### ISSUE TITLE
Check whether webservice returns data

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-plots#35]
From Hal

> Hey, I just walked by the display downstairs and there were no plots on it.  The page was up, but zero plots. I'm guessing the webservice didn't return with data, but we should open a ticket to check into it. Not certain it's something we need to ever work on.

Maybe we should have a check on the page to handle the case when the webservice doesn't return any data?

2015-06-17:
I saw this again this morning. All other parts of the page are showing, but there are no plots.

**Comment by hasimpson-usgs** [comment]
Handle webservice errors and display them to the user.

**Comment by jmfee-usgs** [comment]
A couple whitespace issues where error message was being formatted.

I'm not sure you need to describe which channels/observatories failed to load, I think something like "Error loading data" is probably okay.  Possibly an accordion with the actual exception message or xhr.responseText ?

Add unit tests.

**Comment by emartinez-usgs** [comment]
Consider using a message view?

As-is, once an error occurs, the page can not recover unless the page is reloaded. I think this is because the TimeseriesView is attaching an `_list` to `_this.el` and then never again checks to see if the `_list` is still attached to `_this.el`. When an error occurs, `_this.el` is emptied out its content is replaced with the error message. Maybe want to rethink that.

**Comment by jmfee-usgs** [comment]
Another option is to show the error status similar to the loading status, instead of replacing the applications content.

**Comment by ehunter-usgs** [comment]
How about this PR? I created a separate div for the error message that gets cleared on a successful load. I also try to format the xhr.responseText to make it more readable as a JSON-like string.

**Comment by jmfee-usgs** [comment]
That's a little better.  I think it would be better to keep a reference to the message element instead of repeatedly querySelectoring.  This should probably move into the Timeseries view, since each Timeseries will have a separate Xhr request that could fail.  As part of the TimeseriesManager, I'll set an "error" timeseries model property that can be checked by the TimeseriesView.

**Comment by jmfee-usgs** [comment]
Don't wipe out the view content to show the error message, if it was a temporary error the subsequent auto update may have data:
https://github.com/usgs/geomag-plots/pull/93/files#diff-f5a2e85c3d19facc9af22e65d0aa4c0bR89

**Comment by ehunter-usgs** [comment]
I tried to simplify things by just adding and removing a class on a standard error message.

**Comment by jmfee-usgs** [comment]
rebase
